---
- name: vlan testing
  hosts: "{{ switches }}"
  connection: local
  gather_facts: no

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"

#    - debug:
#        msg: "{{ ports[item]}}"
#      with_items: "{{switches}}"
#      when: switches == ports[item]

    - nxos_vlan:
        vlan_id: "{{ vlan_number }}"
        name: "{{ vlan_name }}"
        state: present
        interfaces: "{{ ports[inventory_hostname]}}"
