---
- name: vlan testing
  hosts: switches
  any_errors_fatal: true
  connection: local
  gather_facts: no

  tasks:

    - debug: msg="My Secret value is {{ansible_password | replace('\n', '')}}"

    - name: Check if VLAN is on the device
      nxos_vlan:
        vlan_id: "{{ vlan_number }}"
        state: present
      register: vlan_found

    - name: Fail if we already have the VLAN present
      fail:
        msg: "VLAN {{ vlan_number }} already defined on {{ inventory_hostname }}"
      when: vlan_found.failed == False

    - name: Build VLAN
      nxos_vlan:
        vlan_id: "{{ vlan_number }}"
        name: "{{ vlan_name }}"
        state: present
        interfaces: "{{ ports[inventory_hostname] }}"
