---
#
# Look for interfaces first and verify they aren't in use
# Verify vlans are not present (via facts)
#
- name: vlan testing
  hosts: switches
  any_errors_fatal: true
  connection: local
  gather_facts: no

  tasks:
    - name: Build a VLAN
      block:
      - name: Audit ports used
        nxos_command:
          commands: show run int {{ item }}
        register: vint
        loop: "{{ interfaces[inventory_hostname] | flatten(levels=1) }}"

      - name: Check if any interfaces already in a VLAN
        fail:
          msg: Interface already in VLAN
        when: item.stdout[0].find('vlan') != -1
        loop: "{{ vint.results | flatten(levels=1) }}"

      - name: Check if any interfaces are port channels
        fail:
          msg: Interface is a port channel
        when: item.stdout[0].find('switchport mode trunk') != -1
        loop: "{{ vint.results | flatten(levels=1) }}"

      - name: Ensure ports are configured for layer 2
        nxos_interface:
          name: "{{item}}"
          mode: layer2
        loop: "{{ interfaces[inventory_hostname] | flatten(levels=1) }}"

      # Keep this?
      - name: Ensure ports are in an unconfigured state
        nxos_l2_interface:
          name: "{{item}}"
          state: unconfigured
        loop: "{{ interfaces[inventory_hostname] | flatten(levels=1) }}"

      - name: Build VLAN
        nxos_vlan:
          vlan_id: "{{ vlan_number }}"
          name: "{{ vlan_name }}"
          state: present
          interfaces: "{{ interfaces[inventory_hostname] }}"
      when: inventory_hostname in ports
