---

# TODO
# How to handle a VLAN that already exists on any machine?
# How to error if VLAN exists?
# What happens if the definition is *partially* right and we create a legit vlan, but not all of it?
#
#
- name: vlan testing
  hosts: switches
  connection: local
  gather_facts: no

  tasks:
    - debug:
        msg: "{{inventory_hostname}}"

#    - name: Ensure VLAN is NOT on the device
#      nxos_vlan:
#        vlan_id: "{{ vlan_number }}"
#        state: absent

    - name: Build VLAN
      nxos_vlan:
        vlan_id: "{{ vlan_number }}"
        name: "{{ vlan_name }}"
        state: present
        interfaces: "{{ ports[inventory_hostname]}}"
