---
- name: vlan testing
  hosts: "{{ switches }}"
  connection: local
  gather_facts: no

  tasks:
    - debug:
        msg: "{{switches}}"

    - nxos_vlan:
        vlan_id: "{{ vlan_number }}"
        name: "{{ vlan_name }}"
        state: present
        interfaces: "{{ ports[item]}}"
      with_items: "{{switches}}"
