---
#
# Look for interfaces first and verify they aren't in use
# Verify vlans are not present (via facts)
#
- name: vlan testing
  hosts: switches
  any_errors_fatal: true
  connection: local
  gather_facts: no

  tasks:
   - name: Delete a VLAN
     nxos_vlan:
       vlan_id: "{{ vlan_number }}"
       state: absent
     when: inventory_hostname in ports
