- hosts: localhost
  gather_facts: no
  vars:
    vlan: 404
    show_vlan_output: |
      VLAN Name                             Status    Ports
      ---- -------------------------------- --------- -------------------------------
      1    default                          active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/30, Eth1/31
                                                      Eth1/33, Eth1/44, Eth1/45
                                                      Eth2/4
      99   netapps_rep                      active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/44, Eth1/45, Eth2/4
      103  VLAN0103                         active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/44, Eth1/45, Eth2/4
      142  LAB-vlan                         active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/3, Eth1/44, Eth1/45
                                                      Eth2/3, Eth2/4
      200  VLAN0200                         active    Po3, Po11, Po12, Po21, Eth1/44
                                                      Eth1/45, Eth2/2, Eth2/4, Eth2/47
                                                      Eth2/48
      404  tennis_404                       active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/20, Eth1/21
                                                      Eth1/23, Eth1/44, Eth1/45
                                                      Eth2/4
      499  KrisSam-vlan                     active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/44, Eth1/45, Eth2/4
      530  MrGarrison-vlan                  active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/6, Eth1/44, Eth1/45
                                                      Eth2/4
      1292 Nutanix_Repl                     active    Po1, Po11, Po12, Po21, Eth1/1
                                                      Eth1/2, Eth1/44, Eth1/45, Eth2/4
      1400 SIFMU_Prod_Repl_Net1             active    Po11, Po12, Po21, Eth1/44
                                                      Eth1/45, Eth2/4

      VLAN Type         Vlan-mode
      ---- -----        ----------
      1    enet         CE
      99   enet         CE
      103  enet         CE
      142  enet         CE
      200  enet         CE
      404  enet         CE
      499  enet         CE
      530  enet         CE
      1292 enet         CE
      1400 enet         CE

      Remote SPAN VLANs

    cdp_neighbors_output: |
       Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                         S - Switch, H - Host, I - IGMP, r - Repeater,
                         V - VoIP-Phone, D - Remotely-Managed-Device,
                         s - Supports-STP-Dispute

       Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           mgmt0          174    R S I s   N9K-C9508     Eth2/19
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/1         141    R S I s   N9K-C9508     Eth1/1
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/2         141    R S I s   N9K-C9508     Eth1/2
       JER-LAB-N93KSW1(SAL1816QV7Q)
                           Eth1/43        161    R S s     N9K-C9396PX   Eth1/17
       JER-LAB-N93KSW2.jer.lab.local(SAL1816QV7X)
                           Eth1/44        143    R S I s   N9K-C9396PX   Eth1/21
       JER-LAB-C6KSW1.jer.lab.local
                           Eth1/45        173    R S I     WS-C6509-E    Gig3/5
       JER-LAB-C6KSW1.jer.lab.local
                           Eth1/46        129    R S I     WS-C6509-E    Gig3/6
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/47        141    R S s     N9K-C9508     Eth1/47
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/48        141    R S s     N9K-C9508     Eth1/48
       JER-LAB-C6KSW3      Eth2/2         143    R S I     WS-C6509-E    Gig4/1
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/33        141    R S s     N9K-C9508     Eth2/33
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/35        141    R S s     N9K-C9508     Eth2/35
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/47        164    R S s     N9K-C9508     Eth2/43
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/48        174    R S s     N9K-C9508     Eth2/44

       Total entries displayed: 14

  tasks:
#     - debug: msg="the value of pattern.txt is {{ cdp_neighbors_output }}"

     - name: Read in parse_genie role
       include_role:
         name: clay584.parse_genie

     - name: set neighbors fact
       set_fact:
         all_neighbors: "{{ cdp_neighbors_output | parse_genie(command='show cdp neighbors', os='nxos') }}"

     - name: set vlans fact
       set_fact:
         all_vlans: "{{ show_vlan_output | parse_genie(command='show vlan', os='nxos') }}"

#     - name: debug all_neighbors
#       debug:
#         var: all_neighbors
#
#     - name: debug all_vlans
#       debug:
#         var: all_vlans

     - name: Set my neighbor ports
       set_fact:
         my_neighbor_ports: "{{ all_neighbors | neighbor_ports('95ksw2') }}"

#     - name: debug neighbors_ports
#       debug:
#         var: my_neighbor_ports

     - name: Set the vlan_interfaces fact
       set_fact:
         my_vlan_interfaces: "{{ all_vlans['vlans'][vlan|string]['interfaces'] }}"

     - name: Show my_vlan_interfaces
       debug:
         var: my_vlan_interfaces

#     - name: Set vlan ports
#       set_fact:
#         vlan_ports: "{{ interfaces['n95ksw1'] }}"

     - name: Set overlap interfaces
       set_fact:
         trunk_candidate_interfaces: "{{ my_neighbor_ports | intersect(my_vlan_interfaces) }}"

     - name: Debug trunk_candidate_interfaces
       debug:
         var: trunk_candidate_interfaces

#     - name: debug vlan_ports
#       debug:
#         var: vlan_ports

#     - name: Normalize interface names
#       set_fact:
#         vlan_interfaces: "{{ vlan_ports | normalize_interface_names }}"

#     - name: debug vlan_interfaces
#       debug:
#         var: vlan_interfaces

#     - name: Get trunk candidate interfaces
#       set_fact:
#          trunk_candidates: "{{ vlan_interfaces | difference() }}"
#
#     - name: Show trunk_candidates
#       debug:
#         var: trunk_candidates

     - name: Get trunk candidate interfaces
       set_fact:
          my_port_channels: "{{ my_vlan_interfaces | port_channels }}"

     - name: Debug my port channels
       debug:
         var: my_port_channels

