- hosts: localhost
  gather_facts: no
  vars:
     contents: |
       Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                         S - Switch, H - Host, I - IGMP, r - Repeater,
                         V - VoIP-Phone, D - Remotely-Managed-Device,
                         s - Supports-STP-Dispute

       Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           mgmt0          174    R S I s   N9K-C9508     Eth2/19
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/1         141    R S I s   N9K-C9508     Eth1/1
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/2         141    R S I s   N9K-C9508     Eth1/2
       JER-LAB-N93KSW1(SAL1816QV7Q)
                           Eth1/43        161    R S s     N9K-C9396PX   Eth1/17
       JER-LAB-N93KSW2.jer.lab.local(SAL1816QV7X)
                           Eth1/44        143    R S I s   N9K-C9396PX   Eth1/21
       JER-LAB-C6KSW1.jer.lab.local
                           Eth1/45        173    R S I     WS-C6509-E    Gig3/5
       JER-LAB-C6KSW1.jer.lab.local
                           Eth1/46        129    R S I     WS-C6509-E    Gig3/6
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/47        141    R S s     N9K-C9508     Eth1/47
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth1/48        141    R S s     N9K-C9508     Eth1/48
       JER-LAB-C6KSW3      Eth2/2         143    R S I     WS-C6509-E    Gig4/1
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/33        141    R S s     N9K-C9508     Eth2/33
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/35        141    R S s     N9K-C9508     Eth2/35
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/47        164    R S s     N9K-C9508     Eth2/43
       JER-LAB-95KSW2.jer.lab.local(FGE18410JP1)
                           Eth2/48        174    R S s     N9K-C9508     Eth2/44

       Total entries displayed: 14

  tasks:
     - debug: msg="the value of pattern.txt is {{ contents }}"

     - name: Read in parse_genie role
       include_role:
         name: clay584.parse_genie

     - name: Debug Genie Filter
       set_fact:
         neighbors: "{{ contents | parse_genie(command='show cdp neighbors', os='nxos') }}"

     - name: debug neighbors
       debug:
         var: neighbors

     - name: Set neighbor ports
       set_fact:
         neighbor_ports: "{{ neighbors | neighbor_ports('95ksw2') }}"

     - name: debug neighbors_ports
       debug:
         var: neighbor_ports

     - name: Set vlan ports
       set_fact:
         vlan_ports: "{{ interfaces['n95ksw1'] }}"

     - name: debug vlan_ports
       debug:
         var: vlan_ports

     - name: Normalize interface names
       set_fact:
         vlan_interfaces: "{{ vlan_ports | normalize_interface_names }}"

     - name: debug vlan_interfaces
       debug:
         var: vlan_interfaces

