---
#
# Look for interfaces first and verify they aren't in use
# Verify vlans are not present (via facts)
#
- name: vlan testing
  hosts: switches
  any_errors_fatal: true
  connection: local
  gather_facts: no
  vars: 
    ansible_python_interpreter: /usr/local/bin/python3

  tasks:
    - name: Show a VLAN
      block:

      - name: Audit ports used
        nxos_command:
            commands: show vlan
        register: show_vlan_contents

      - name: Read in parse_genie role
        include_role:
            name: parse_genie

      - name: debug vlan output
        debug:
          var: show_vlan_contents 

      - name: Save show vlan parsed output
        set_fact:
           show_vlan_parsed_output: "{{ show_vlan_contents['stdout'][0] | parse_genie(command='show vlan', os='nxos') }}"

      - name: debug vlan output
        debug:
          var: show_vlan_parsed_output 

      when: inventory_hostname in interfaces
