---
#
# Get a copy of each switch's configuration
#
- name: Snapshot host config
  hosts: switches
  any_errors_fatal: true
  connection: local
  gather_facts: false

  tasks:
    - name: host snapshot
      block:

        - name: Capture the config
          nxos_facts:
            gather_subset:
              - config

#        - name: Send config to output
#          debug:
#            var: ansible_net_config

        - name: save running-config to file
            local_action: copy content={{ ansible_net_config }} dest={{ ansible_net_hostname }}_{{ context }}.txt

      when: inventory_hostname in interfaces
